---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAao45yb4DRtMnSoV0C7VkBk01qY7NHSGP0QQSOPoJfGEVbij7fFCF8sWrZVFU8lmoUTMlefMBiRRTFWuucWvHSh4aFENcfdpTQJrRBKt2lYxnX44J3e0wdai3M1wodO8FAbesdnWpY+EYOOUrlqL9CzXRr1sBZXMld7Vo1DlqD8JZMSAz0j7w/fwNVsDEj57ADtXWWU+bvBG/4SZMri4iWzjBR0J7Zjt+b+zPc/XRYaTIeSYNRZASnxSlRkxSuTEClZjZByP/SncFeN04PBNc/bU4bEAGHUczq9yrIig9hTZfYT5/LKFQzhVFeN2PSbDN0ECrrwnk0rM+/kWtfejI5Y1K25ic6oSktPC9kHlHdJ/wtEJUYOW4r4N2vUZ4ka+qiRjq6dVqFX4IplIVea5v15fSEDdt8ECqEZjBdLm4wdn+7JeZfmAO6GW/mry5BtDwjBgbbPojvFY3f/DIIRQofia7URjtio/DWepSIKk26r3GuI5xhRUwIMgPBSgUge/JbjQxUCb5bI/9Nop9GqB9IoYBLidAWmSTchKR9ULafUi1fo4DhkjbmgiWnAl657jEBk8f0se+xmglcFYHHYqYyPb+ZO3oSIbhp7AHucrI47b7sLzSJ1ZoqyyBSagpR2VOggOjtQddoDu4hpUKnWGOu/NUkC9chiwBRPH/Jf3Lm5tOWRUchBJBZ4Sf5PCKy5nk0g6NfdSgYElEslGykbEaDO9XTvknrlooxENjtyelzvA==
  template:
    metadata:
      name: n8n-encryption-key-secret
      namespace: n8n

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgresql-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgAoiGBBYcddfjwj/Trbm+12bSzGH18jiFvBKvCgPbfwh7I8ttJuALshIAiBKpIH5SFLh712T2PNs0zPGJLPZS0Ju0Hr2VqG8WHw2UR2yxFXGL2TxRqoFXdBElF39P+0O0kzLpnib8q0umuM6wN+1BBhuF9vaZ3xK4rR44Zlq1OW7nucFaMK0Vdjs/1Lq/W0vNaSZdnji3V8HtgOaPLQ+SR5C9VAfVIJwI6NqTNZG4DwOfQaIuSmkFS3tL35hO6HyFPlySAyYZ71mFlwqKfjkRHhMj4pAmlQREvhOtfz+lwNWXnk+r5yjXjGux884KuTknXMjbR1p+IbwB4ptj0FlTKrOVIxji4yMQIw8gmD4wr2EV9GlZfga5FajSKzQWwKi13SH4u1LGJSdfaOlB+epWfGg1uD+DQ7RHjEXqWNOiyHdsTkRzo+O4ULPgBFe7Pam6rIT++jspzsfnhDcnhzjv/c9XeYbvnvGeaHQEecUifDSbQC5vVX3mlNVZB4fJTAq/0SF7kDWyOh3vkkgPscLnWVuohM78y//rxUnDTe0yvBLe7FGyCFtlLpLbiikSotVo6Gybbbc6fImbqkRSWEaVxzmqLKaHSOeD/MZYoYiv4QbxPh13VpWknyAtaow7pJVOmOPraDt+/5xypO7c0VonY5O8pPzN5cd84QvTpEx0LtwE7Q+N0d5vVHUrmLkfLZa9pB/S38TqExZZwjI1qcY1ATDXmQaxUrG0807kfc0H2W3A==
    postgres-password: AgA+n7UPdD1o8m++/IafaLoUKLQ2SiFgYiwY3N15zf0NKdLLdZIIgjccAOzqbA1Ylzp5K2omIJYqObCFn988cgN0iKts+WskW7jeRDFWOmUwBUTurdPWeZSqZouxDOb9CDRzaY9ueQ5py/w8MeJBnz9LpopoQ957flCK13eVNtO/mnHcTUqJCEzDDKNEYEjkde7Egj+Zfi6NlzlUQhOXCU1rLeQTdazYGXQijO7CAVGxtCSSCJc/bkFvpnM068RiICQYo4z4LFWp4H7ZTu9KHza4xBliUmwFp2NqwYOOKaUm41VrOjc/Mnbc0Z7uP760NftU2jJPMEGwRg1yy6QtTjJ/giZ+k3Nx1U5Bi0wpBEOYb9VXJ23SnPzb3bXItCyPbFU+0soCBILB9m6Bwtu05mBqRaeq/WN+4j2pVkEPySQcJyn8ymFuOD7igT7ZLzc+bA+tysEBsDrh+xqY5v599f6fSYmoyrM7ZfhzXICZjoCq7H/3hZhjMRGa2HLOrglEJC5VXoM+OpSu7uKszpDthBDf+8HMp1k7zJ+JfmLTS8sdf6ldG5OxwR34m0xpx4Jzdjvgv+aDJ+SheVDzPm3HOmEetEYSn5wuAixN7S+kd5ELwlzSEPIinwbUbHEbrwOdf7pgVvYCgdUkXBvRvFTLmIuOIj13DI1FABQ2MXlJS4byJ2JnqiI8Q5UZWgLuPSapjNqBxyrl6RtwRPv+c9ZwWO9qYHqvisFYa+W/YYKKR0Ktyg==
  template:
    metadata:
      name: n8n-postgresql-secret
      namespace: n8n

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-redis-secret
  namespace: n8n
spec:
  encryptedData:
    redis-password: AgCOn1Tdt8/qpsO3C2Z+SG4KO9Q7podYeUA4MtRM4WDyQ9xFTqBzAQSLB4fakrgeGB4nCdbCP/VuWzyuNkIbRK1cDwRUPc/tJi/tCqjEchbDnoe5MhQQrXhnrMyYBsdov+p3lsWASusDiFptC3ylPO6GSw8WfarTAlkibal64VA7Fs9mMyrb36+rSi5U1mWXzn0JVkLZlxGxPJZyiG4zRgbqJjRSLk6+xmWdV5WvdQvjdvpFRbz6HVbUTcC39Kl/Exv/bBCo2HrOuVFG/uOPgqVMPevS479vO4Al+o8y+CErU/eeQk1AafkWqmrMVkqF68sP4pKwwL8blgEhhQH9KVwpdUmokxadYCuGQlTsliY6EbXvFn4fGT++4Pj+8V2dyZ2mig7GbzcX1PxOG9ckLVdKrGqz87QIbWHKkLm/I7XllYa+eTYe1wRtbn8Z0C0uNEx72VbO+e3CpUwb4gdtwG24v3vipS2S08JpYKTAYzBjV0ce7uoXK1ckp8Ihoz4kHXQPXZAQj44Bn5vfcXhMJIr1R3RBjO/EyC2YFHMHV4CWK4l3ppzaF5Xv6fyvdYkwHC45eq4BAMMtcrmyJxmM4KhmHQR5+y/tdaFBP97JIy2WGhq9bdTk1AKZCaKYmaI7WInOG2+AEPLO4z3tpPqJMd8m2ysfcZANTDRfSkC2LlO5NQrskM4Ta45LUFDBCtsZ+kJV1PsmTGTD2yXExi4i6v/ptfpmVaOy68b9LfCDh0j42g==
  template:
    metadata:
      name: n8n-redis-secret
      namespace: n8n

