---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCvnZb7IHTd8JahBHsi9VQOzlQrRghdji1FxW68PiHgXNOM5Ee3b2RR6TyXDTeHGLtx8mhYk/dQ7KKTwb/y+5Xce4vGBvZ55rzfz1qjAz6IifOTxH5MGLLTLdcf3/JDKbZAk19xqMjDlGUX1Df93ArBxEjbXum23VSEKCdlA+uWQ8tt6JzReoiti8zSjCOdjhQ6uGcxIbUbzivZ0i8HjOi9KpK0Tbv2llH1cJOtWuV3ftcepKYU2RAu6hahZUMx/h6gMUoUhGYqOrGnRlqLCsN973tP8Tn9p0xy0SsK/PPvSqUxqghbT6bYG1wbo16xozL8K5bH9X8oWK483PH8/t56vg+c2xoaiNmYNlCfL6feja2pXRb5ktFJmxVHDmbaiMsbSnucVI9VkwHT39CxnqjQqqxNYrs126zkdSKtiFCBseP3AD3PvGkWAhBJendGS5zAd/DehiznhFZY6aRd9exZeilol8XQP8q0zfntagNu5cM+YNwL6gnlkwN/iMB53EEaMNj30oeNJ/FuMvS0UTo/XH5INp1OamNwliRzbPYjPnL+4cQRNciY0AU+8cmvyLytTANbLQDKSvGg2pJHa/rEcAIlkWJBMMvsxHjb+beuWdoB8BQATckENLl33k5Z7q5fq5DwYa/DQyjc6pmgYOoZyrfNCBpum1CZFIBNI5FKCOEHStXxdMBo+OmOqQrjzDdhuTaf/CDERFw5+Xzhm2CE5yjTu5j6OsClAiR74C3TVg==
  template:
    metadata:
      name: n8n-encryption-key-secret
      namespace: n8n

