apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vmuser-redis-crash-logs-kustomization
namespace: observability
resources:
  - vmuser-redis-crash-logs.yaml
  - string-secret.yaml
