apiVersion: v1
kind: Service
metadata:
  name: cluster-discovery
  labels:
    app: cluster-discovery
    app.kubernetes.io/name: cluster-discovery
    app.kubernetes.io/component: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cluster-discovery
