---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-redis-secret
  namespace: n8n
spec:
  encryptedData:
    password: PLACEHOLDER_NEEDS_SEALING
  template:
    metadata:
      creationTimestamp: null
      name: n8n-redis-secret
      namespace: n8n
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-postgresql-secret
  namespace: n8n
spec:
  encryptedData:
    postgres-password: PLACEHOLDER_NEEDS_SEALING
    password: PLACEHOLDER_NEEDS_SEALING
  template:
    metadata:
      creationTimestamp: null
      name: n8n-postgresql-secret
      namespace: n8n
    type: Opaque
