---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAm0ey90ADfKTp+95AV+Iu3BXTpp9RkAofpsQZABtmkTjOwugSMGvZo3vIVqKRjzB3P0LQycasT2QXs4YsJpptbhpvcASmLcPhIf/wT8gTDu0mkcHqpXkJTlGOK6b2AMWxvbj0tl+ENS8x2+JhDVJhbAFAtJDaBTKeGAnBp3xudWHGKHS1/MLHPAfzgJJMx99ACk44UpoLaq8fBGePOfRLlpPIDcdwgRKx/xdTnh9MK1AGmoKrdhpBUnT7Q39jS1Tz4TRksC6s6wU47VpCCTea8/yQp2W9Pu/b2hO9f1VjE2/ZCa1edGEd+fJWdvLz45kvRRkxwWvW/T8YpkyymChjxwnkkUPjEAUnNTexa7d1rxxxRe6WBdT7dhy3Y3C2pYqDUzfIadUS+QYNo4+/1pex768+7lmOK6nHKdxnjOm6DYhJqTwfMBbhZG7fHwIgpTZOMGm0b2rSYstbVuATC24k8vweTzVJzP9+ReqroKY/QNOnI2KmalVvczCdvwUj6Inp248TVqDnpKCa20ngDpipcN5zKMiLRLwqXkBTtQTSaX3i3ihLeeU00dL0knnr4+gjIvSkn7ZZQgc5eqH+/dslWhQ7FfDPLmuRYn+vFNfkezJIUfTK7VUe1DcvbkNLjIl1eFVJq8cxR5X03B2f1fLA7yzqjABYt77vio8RfjOZg2q8QnI9WhDFJPMqkhtFKNQEhwd2r/tAXWNe9f+r1h/gk8lk18snemuOnNKx8PKnDOw==
  template:
    metadata:
      name: n8n-encryption-key-secret
      namespace: n8n

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgresql-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgCbLsl4P7wLwpnWlmTv8u99bMMf7rpGiasX3yq7HH2q7vXZSLkhvGpAGERFyr4BTNS36spxOczqKxOd8Kv7xof61PiTQEAgeV7QXc9UsorioZ5o7SS+j4u5TCn/jzC3d1qXCZ9fAv+bAaj005ksmlm9Ln3XkJcQ+DIMbS0d1ZkC/sFqWZiM8fqTq5lEDvtukOOeB/+gnVyozOn5iWSeMF5nZt3t+N8DvEzKdf6RqIRV1aUxf6liZx1Yr8ZUsKxddESBIM/92E42CYGwIRAS1smOJC0dVKjUU7mJuI63Q36+R6C5JYhHSHZRx0xB+plewUvK/N9nrSZg9LEaIw9eSz3oc8awS1hFU0SCSmtadB6PNZBfR56Tw1M5JGp4oqUHjBAjKubWJL+sAEwtRY3+VDMp0HpwkMAsFR9iTUA+j7iaNmslwIpn191ikBkGwpKqfHRGAz9GnXbfzD4AQbSJVnYJl2cPj44K924DasAFRTBNUsbPutZS/JqQbsucIa/gaTovqoK5WqFagGGWFH/6ziOrpWzS/mtjDylHJqmKvO3S11s5dlscBswScQAxWMetTz3RHEoxM7gBaL3RUsLL8qFvfYOo7SYrg+5b7SNZCdrpVQC/pfsuVqmDWOfKwzEUrXsr/XpJPyGxBkSOaMsHyzT7waL3N/1b8F7jHP8mcmmh6oRJ6Oi6jmhbx0u91+W8+tTm6xjIru/4kwH2LqYhmXnhH9gR7mE2A88Y2q5krXevcQ==
    postgres-password: AgBClfVHWm1Jr7Hx9sYgWeOfumsr6YhC6VHWifHSuCSJrmQS7VGctTXcPnJueGPnZKpieEFMlKmEMrlZe5+VcDPFQACOCfW+w5C2yoMxrLvMRyCr/S/ekz6xbV6LasfOv6GHQL3Jp6QwwZNZTQc02jMPXhCEsN0RZmMBqPTA3zPYZhyc5WHdGlIUN9lLP/AGChSaV3j8o/hQKcABZZicUCAvezrrRPDpDReQ5ecWw8CA2kjg0r14e4BzzjPAg+yM5uVBQYRFU+k39Tl20cFk5Bjj2jIHnspI6/snuRDlNgLX9KK1Hi2zv/wDRX9DlfTtc/aHs6T2h99M9dtZoYRZVOqk1uiaUICsvmazDYbxtts/1nS6Mz8Q0ktvu//YQ9TOI/H1nkBBjtdPSXV30KMBKerkGQfLfHAl+i02jguB0I0XkFhrgOnZYQR/QuwXZvP9mpGnTFtFw6FAL5CPDRSmXlppD761XjpbLOgWMXNHDLo+Vy1JQ6dltXJMJG52+CzX+95baMc6yCxEOKGAXUl8ofgeanOFpfRHVDTpYh7f3krt+n1/rp43PJdQDQeMU81FSk7I8mZJ2BHxOWHktKT4Ovq8C0P0nyGMkdpcTdWBRjOl1l6FGAjrVLUU375KaV16VqBMwQLRphePsNJyK6Pm9d2PqnBc/LKb0UmNCJ416+TP0U72nLSW2Hv1+XEp7v6FrADar5OoCpxTmhsOflQYbKvNEGsOF1Y3zB723kT/YSHjWw==
  template:
    metadata:
      name: n8n-postgresql-secret
      namespace: n8n

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-redis-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgADBoiJjLMb54f1jXYkYqjg/qnkP4/DJlSZLFo/90nLusJhUeRlq/sE7+/OnyK9Q5oZUnRnl1JbqTqPRd3bNZchGwCmcnJuX7wyMDJPUHPlBOXzZWOimnxLZonChUjMp29xADK/I1TtDx6u9tBpeyvK+GrqZSZxKxG8lbAR2NmIG7ZtFc2GFQYON20+S3m0bTkEepvkTqkw1WXMRZ1uQnomNtalwe720VZgtCKIiqMXNswtblRPJnMH3kp9vuHSEo0dzTtf9+6D05w5cJDHQKiXQX7c2To57fMxaY7WhE+/nxU7ewkQt47CBvSW8PLVTS866f6X61+muvqjxypss+dnnEnsoE1ZXuRrDIoImd1k+3iU5t6BD33xDFKaiOD2W688Jaw8jeRP219VyIJMXihapb3JgPDHZgviArs/8B21Vb0YyggtlKMOHBOneXoR1x/V022q0npaxXe0o6FqjGBYOe/iTeQzCL2NbeUQwmWcNuDuK8PiI9LCfJLdn5Q3Tbcd9DDSYa97CM7tNan5M5e9VkItu7AhsOA3R26yC8I/ZgqVql/u1lQSO48l9cqZXIUMnaIUGkRMGl+KpuzSbLB2IkO8IWo8T8mGBNS9wgyjPNV/9laUPNL0/5O+CnMb8GlMZq9NHVAcf5P5JRLYB9KvJQkgK5KMXFGEc3OnaYWfox5EK2Jq4mUHYTDVs5mQTSIHznEy0BySN/UYhVf6Gwskf4i1DTL1VFn3acx3qzcO1g==
  template:
    metadata:
      name: n8n-redis-secret
      namespace: n8n

