---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAzNawkqV76NvbptY6p9tBAFZQnmKMHB5GK2pbR2zg4/giNdItx6WJreM5rB1KS4DG8a3+P0VwLcpfswaFAH63SKu7yEM8IgjjnIaEX2bJlZ0KE3HjK+KOYAXETbTz88DJwvSv4cUBej6N1L4cMbmertRK/Rbsn3O99miSSg49IzYETcK9jc68H6ODapRy8ch/jP7wELohveGTPczOTJOcFEVsKozME6ZoBfFIHsq7JXQy7BD2L4/7oWy1v1K2FmNxD++BIwDZp4HGVWvMF0DcFN2PZz81yhFgEs0jQ4jDQz9cFpSfBi0mtXGkjWFi3fpRcxfQFiA9G4GdZcOIwF/UmGr6ABwDdLRXYIWN+ryUFOLbEGcp+aHdNGLLRRtswQ/F52RPEPdAg3hnsjDeaT1oqS+TuNFFxEYjtUQrRQ6j7WDI0q3jHk6hJWNeazKLo4hP/OszpmuOmjY6XINeOUIqeecL0cU2grXCm6N1QzgmFvx+uucAHdOiiaLThqHyZjaU/Wt6qJG7WD/A9fM6H23KTJBhiudgTOfAaReM1lpNNpXSdHQB7hco5ht0Z2xl1LrVoPBckRhMDNTEhpF02LMMBLxAGrbz6lo42ny3/O4fwRKdkSy/Gkp+xXbv0i5YQKoRhVzwwKg72PRXCAPGzZBwuwlamsaB3ykkgVgVl94t95A2LeYwtqGiCrGkMaNBgukoWeoJR/eaBh+ffFIF7wD6jeXOHXzTdUpVTUcn3fVR8qA==
  template:
    metadata:
      name: n8n-encryption-key-secret
      namespace: n8n

