apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
      name: customer-ldap-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "us-central1-docker.pkg.dev/ctrl-plane-dev-f7a2434f/backend/customer-ldap:dev"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NODE_ENV
          value: "development"
  - target:
      kind: ConfigMap
      name: customer-ldap-api-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"