---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-crash-alert-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgA9osbUhkZRFSNOr/emrrQb72Qt7c9twGaao8rLhU7yaZcTmiZygIrbIPgszAuCPxkfKqBNXpdcJKsLUJ4NHTOJ2t6a8eY9IUDJB0LT4v+Q1UEBCtJy430M90bdFrl9itIWwqiyeZm5w2KsmC9Cjods5lu8FR02inO1f9vAW2R/K4QvADFo+qoAdvsmmBnGV3eW7lA8yTF9aN60epsGqhgLY8mpLMYQPGPVQI7HVNmlz/5jTHTKA+BPtpqylcZoa9/2MLiEgFCQjip3FQOZNj1JLjRLwXnRx9+pQu78a/Q7g8v8tp2XIwC/tynI8grjOW70XhHnHNRxhYec9xziXnsUH5AePJWnZn13pr+SAHkRVmgEJPfBurvosgkyJHTwTmbP86heB4LsoYobFCAfjZLnysIXaqUrpft3btOqu/j/qZq7HDG5a9omH68W856k6H6jx7lj8ckRXcCKHBEAHqAhPxW1y8J+0xCl7K2OWUIkOWLvr0urLCEbkBvgDxAWWoNdhqjde3R+QEX0LEyUrzyOPEchpSe4KTBGluL6iUSVaBxExXpfw0ZaSFg92yrWIf1wvRCCm1RgoqZglCibTV3mQWi0DJ/XQ2ODDwvmAwpwNrAFusKtS3TZ876VZ/xJWnyCTA3kkTyflPj7otXOM/WZgm3PCU/cpQtEvfz7dFgk+GOxtYwwRmUS6+bS0yvrQRSH1GFdFwNcO5ZXIbTyfAkR
    url: AgBTBHtoVKjqjjeQcnPZFMpgBf5h3jC+ETvoeS6KsjJ469ktR/JSaR2oEw+oj93WjhJxw47L+qBMeztWGRIII/AL62U4Y3G/akLJkwO5XYDCuA/uEUoNby/rzDl+x9T0Mfwsuo4CdB+XDNF8FjIUXZIzb6obhTT9ripKVM9tfLf87NctDYJ2uaI2XyMJXaCn8ZWoypJB8chEXWtq1q0NMDAMGhCiHqXBSV1Hw4T20VW6cgV+2J3scOJ78QNnR19i7qxuuAgJjqyMVzcyDNDGvBeJtcf803NsGjDXMK/exo+uUJR1veZ+coZh8zX4CD5dJZpXXWcPunyOpqm2l1Up7+Iit10tjkDg3SDOxgEwPdzxyy5eCugUXQmuBQVleUhELoGiIENM1Npr709mi5jxtFYivVYxjrI0xKvoXMhY2ozTcyS0Ouziez1SfIAwPwrHSWl1GEUjIMvPiroUZlHZiNlLAzxfZfKQa9uoPSBwaXrdL0g250/6aTkTa2RqlhIGn31ishyBNFODpjEeK9oTOCQ0pYzk4tgtJiC/FiI4SofzwV4CM9QwW03lGLsWd8B4CeVsMC+fLCqwWNrT76Rub9XXsmTk3l/zK7O98qEnovm9hWYp/G7wsJY8kd5jGPP2D5vHm42w0CkMYHVjzhrJH4s8cZLrko/60F4ejAxEYWAABFlq1V6ff4xWqkpwrAsJ+6eR1XU0PgmZKgTJ2NxP34D3x7mYm2oa15Nmoeze0b8K2mIt9lBuapTuRyvu4AU5yWKm31V6qOZl+YdOii58GCwhekR8Qu0drXQkmeWT2w0ipS1SreysUes=
  template:
    metadata:
      creationTimestamp: null
      name: redis-crash-alert-env
      namespace: observability
