# ---
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: redis-crash-token
#   namespace: observability
# spec:
#   encryptedData:
#     token: AgAccicwwYfuJFaMyQQTRRxK3umnIoN+sG0G2DKhHHoGipLM+TdwmSkBFBxwsLW0JNmD++8/YxB0U6fdihDHpqKMVNr6f/1AzNmD6KIc5B4RKdeblDMvXtTjW4Wm0QI0DYsLeK9t8IC2kIyERoEKtFZoxkY4BRpj523vLfMFaArYd5KhV3Jp3nqMWs3+gSn8alUnsRz8crOSKdWZqer3OxWDK8n6a49ex8f/bbd+rqWUsDeyu4YwwsLHQBxHOfIhCwgE6OXyJmqs2p8RYOqurD5POVoTeT2cfOGLNlKRSWhrVzayj7142amevNp6R2bsFD4HcAPxa0wBctudDWMZdl3map8Co+4swRBj+IeR8X8CelGk4VjD0iC9Vfk3iD/6TY+LjN7BrHG0+RaSF1Va4UGO8dBqcuOiTvstETzW3svhWl9+zuzXoLXopSjSwY0/gak18n19Q0fRFfSwS2ocvIuQxtA5qA6riIqCJUiJ6CU9Vz4E34B1rzWPpetnt4URFTY9OLR+kSDi3tcza/Omu9v9ombdfG1Byu3yXHMbktL3ciexxQ0w38Mm+l1zkJ9dAB7xUmXR+svOxrjkPo02eg1/ZVTLDKZgTvuOPcU7juPpP1DL1p7aqbyqWhdslRKt94L9Hn6sROVd/MGxGxXOTYFcyxmxrYuKJfbEPr9dc0oxk4E75gFyg8sLbFXuAi7AnfjGMUVaPK8SHxurwCfUvpV+5ZWsK9lQ3zNp/b7kvEJAIbvRVj04/4sP
#   template:
#     metadata:
#       name: redis-crash-token
#       namespace: observability
