---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-crash-alert-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgAesOAW1H25j2T9v3N1rXn0Ag6igtHDg8ZwxZwK8Bs6wrtRReG5eXC7ZkeLLi/LPK24/wFhriqSlvGPxZPskMhUNH/asBu/x54FGCNMuLv27KGuSEaIv4nzVQi/mGsCr9OiDQhC/ErDZz9LK2TUQBXCfnC8s06Rv8OlvrM/miSfo07aZgE+lW9QDUzZ4tOMx/Y6iKTje6O5Gf2XN58t1X65RXXqwjeoIOkXow1CJa9SrklPcU5V0MIUlekAcXlkcAk6In9h7nsZKhl1t7m4A3DD2GyL4cSjyPLvQ/ChkUFFdh4JgSG8PNFV1jPknXLOwAJ0yJkjs683QSNH2svlqBeUXDegnjk3p/p22dO89U1EqEupVws1OhwLiFbP7JzThQKYVEUxIy81d3t4X8BuBmgb26+2GOAx/Ip1qYxRbq4c7EIuIVxAAaLR6gm/K7kQal5O41bNSiZMECyVqfJQOe4/zQ+d5zhbm1SM7t2/sidpKSChQ7J1aD4BWT5yT9zK5CiRZSefCADJeCMBZIFCj6EXatg/3ADjuY8DWrwQ2cV7KKbFG6wBeQpBUAjUNOLvOGow9pg0clXmhzx3bXwiKcyFYqKMQ7E9Y/I7M+e58IZxmy6/x3KT9LNsTkDm/98sL94Y+eYMXDJRAGihqlBwUjIWYAVVKGx2hWTz+TY1BzfljbnBkrb3Bp4Sg74094yP3OIxrdoHJ4EJKvAFXcs8fK22
    url: AgASrBK1U0zqV7xrMtOXPgB6JEUKFEtdRl8D98WEvnHOGAUdYamX6RA2KibxUKu6qXhYbS7O//xv6Mb/KWiRKuzvONMi9UkZobzBtqFPG83wZlGpAz/eX5ncRYZKhURPOhCi67ZJpfJ3JGHXdTQ1KetVCK8pG5OZUssScLyBJDhRyd/8gBtIGHzZ5ilDqEofB7CgTRa5ZJ+t/V/KJxHddU1AFaH+ssIWWW9LBrUG4HFcED+eEbnyKTXIPHtM26dDWoeY2YzrBkT3jkbJbvCSTMipeqYdp1hxhhuSQtDiudMFDel67lvamXn7Jlqio2ZSFqe8AWU7J463RFNpHUpSkGlqt1ONC3jfTJzv4MUugsI8jabYIrwKmIi8RdFTAJxUiHKzvsoksHhssREoHc5ro16/hegPd0W9OZxYEzCrKvBazOlofCJq6IADyRk1bB/uDXWAoQVCca64BNXvLuCaUR044h0zWgNmGsBk1Yq2QaYtO7fH5ecEMrzWb6nhtruDracf7IMcNh2ZqMYmyD7fKLuIb7dXwKTddnqp03tdu+b3W4o+VsQ8vDFOuIS/rz1BC59Ecwvb2v5xihAXNB9tZngSBZCnjKno8HfXtOSMF3h/hKok+2hbRzh6i0f0O/pZndKmha5tN1DYmh4/F+Qc4RO4tEaDZUiD6VoaaX/cbShaf6Ef/BUFdCnFAWPqYQjkM9v8QdWKb4IhYeVyW56l7JrA62msYSctg1+aFi7yKGEvwmsC9KzythaRDV7fWnp9PMwVZMtRZNBJjtIX6PXlw4vKc13fkZM/8wTcTC6fLvOHeOFofy7Y3Y0cPY/g
  template:
    metadata:
      creationTimestamp: null
      name: redis-crash-alert-env
      namespace: observability
