---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-crash-alert-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgC9CFgigLCFgNOzdZSXw9b2bH4jO7ycM7dQg/s9OLzlrwM8lVPdaM9zyf9hlV6iJ4wf3rIYe3GmlIS4Yhmjl1dBwDMwwyec23DxBTwGAcpbq5tjX1w+iIrPw6C0RuYSbIyjDdmQm54RB2KpM/YAaRf7861DVRgTlbG8DX8JSRk23dTMo3VuYX0QCPZht8XQnV7gBaYYGVJdbk4LZet9vSXDo1YoG9rKrcJplcayZA3HRZbnZI6iTUluroVUFCquk+1EMKissgh5Jyu0S38e1G9xlQsoaVyfoWqXLFkbiIZIwYXIjF44bFVuvwGVKBNhXee224mY+C+8ihmj4/vub3eBxVbcB0OqgtKCqkQWruRlUBAWRE0CzkAFciEzD5GI4PogYCHxKdwdpMojsTm2Aw6EfeaL0tPavh4tb2J+Nd4BNNusR7HohtRR2TSkhGUhFbW8APu5373Y3SSRZWIXX3uuVgnuC/z/77JeSGYbKsPF+YLDFXnTCsXhlPt8bWBup5PpU3x9Yu79n4A4gNfb/2QMTmD5yPtxtGxaLXF++OmfmUf0IYoGZjXNtbe+Z5DwxyTYTn9arJgYoW+zxJfo+/nJIQSzpHyiei8joRwfANm77/W7tqDdT1M5vtfQ7B2XSs86qJpGhuBgr8iL6M93qD0fj6sWHs9lQa1W4ciu8FBVoE8mfi9JiF/YVWzbP3HxjtfMFDvbUrslirlXqFJcPebz
    url: AgBCuwmTd/IbbIj2LlqU52dzcorOMuEsOWpcT0d9B8tewE2t4nMOvGfLouiWEtkPDKivhPf+ELpvevt1cW64kaWnX+Qhmj+gf7W15A9ra9GK3HbDaQilakjOzkRI6nj92oqkVBqGyRznUSdRDcbVUic6Z3SglOTH8S/esm+rHR9KCSCCQgG5aeU4wr0pEZYq2zhlguH+gN7gLHhiSBltX2hRu3qp5Kg37cGl/vvXzXqCn2cU8NDEYe3jeQRUpCGPpwBM9McRFwoSFx346ZZXV4QBoWnpTxEHrkduXg8A/6XvFjbrnLyxNJGT0fH8AQ+RR7ltACoLgoNlGN44sAbDM3rM0DIoWVZflApUBlgj1crFXTGs+i/ulGLD5WwpFeIpScgeiunEZhkBOLQdaVAJQDKdpK31RHBdhf8AezQI2Id7Z9TgUkODLL0gZSZraf9Kqj0/JtwzAtOpDvXTkOuwxxbOJNechct3jjJc1QmoHW8CEcoQHqgHsboEowSnVQ9i++UBJEGpZOZJpMeTGIf9eYRuYJuXPGQ8znt+S3XUhs/rxXcox2Lr3Kh2kupMt4YB5q17zIRaDT2jqKSbhXdTqGTxOop0AV7S1r3GlNAO38lrAHpHH7oBBZuy2n5IYRURgaqp7BSPhQc4ZI+GbzzA7g2FY6meZx4jx1wwVZVLKsGhxClg5Hn6kzZzeKRFbJFJdYertLFPK+2Ypgtq2tbiMW1QqA5EQIpD9d8mcpTEIPYcIJBGakiu8d3Z/j8K1Yl/nGRyvbTEb8I5lyAqYB6ooQh0+j/op1kagw==
  template:
    metadata:
      name: redis-crash-alert-env
      namespace: observability
