apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-rolebinding
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get", "create", "update", "delete", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-rolebinding
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-rolebinding
  apiGroup: rbac.authorization.k8s.io
