---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: falkordb-out-of-memory-alert-critical-config-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgBN8a0ElTy0fPPbzbbrZpcRYotZHTZcDCfy3NNvzrhoqZVgufyMzyKwv/ovv+XkrQut/SBYVbYa6129gEGnJNThxhwIGkrDeBO5wb+/f40NwOW0z9oNzstHPhgjq+K+K+ID3bRBppXDovQ+IAbaX2KxIZBY7bfrTBY1oUz1syren75tKVDL6qlV+0L3uHUx16OIRqYGJj9LccsMk11IjRz2+Ce9GEnUuxtKFz3oasjZ3sjZ3btgJbfgHrcVgMCjkwiYSEG7W8hNeQMVgj3x/nqB83L+1VVvXzv9ycsXVFMD6x8EPGVKYe2pqoEV4kMkrdP3VCPLQnW80koeoy9wmillPQac1q77Ck+MW7C8TnlGQF0Wd/y/pjUiobM2cHiYmRaMuM7aT2IGRdp2UEOX1iYxaKynx5E2liGC1uH+U6t1jTpwwt+IFHlgD3cYN5RjSsViV76/CnU1cGPc+H3OEbOoRK8Od4aIdHdvydIX9UqHn+bTlxEjEsx5bZOSgnbECZnu+3vioep8cbKCx6UAbPqavI/zEhaMmDnJGFESUHsyeWR3nmv1jKnsgAQY0jOH1dIlnGDD7AY/pVf78C0K6v4J8XDVZhXoxu0D8FPS9VjS17jQ/1BLBZSyXHj+DjHXlf9SZiPJlbBHpCavpPRtz4TAjBFeOt5tBXROpQ5+JfW0AIYsyY+ZmH2b2pXOcJoRwhMyA47LFYjH2s1HeupmvShh
    url: AgCFF1qNkEH4ttYsA4RwFig3bsBc2clPwaBsduROstMqGFz+lm+MEAGskOlDZoVNADgmI/fdt8fupZMBiw9N/Tz1+UntqeR6afqmLZ+RTCVYKVhHYEgcccUGlHw+USPNL5rfCjTSEcaYQTEwquuQz9/be2M0lnMSQHjOdchIOhpkgwpSPu3Elv18xDINwXYbw6TFYnvtWIDMxyz+Hub3cfckDoq4l+Ip0nhw2bWXCK+YkKACy3USd70bHTKpKJASm5qL0R/aagidlcCXWVPJjAx3vGJHZW4fMS34/9dRLkjD7618ydBTkGVSz0aeFzB/+Rxq85MfNBOHrc29BirX7/VXHaSkry5P6fUhHjd616zB9ZR8Umdp9KKiAucs4QDXu+m1/KTOoYYUui9QMDVqdJ0zn2xjMC03jAAFKSyY8rNlaKlePM4Xz2w0vwToIg/iAu7SJr82ciR7A/RkK66nsYolqhJ5FNonE+qCnlCABQI1VdXTKHUuXha2hQweCFYIivNmPLz3N1MRRCxGBbeS6wYu/dN90MGDWzCZYP2Dr0TIdCJnCCeBdZ9KiHHbdjA7sLtN0fnldGog9Scc0I53uIvtYX0rvo9spN41wF5f2p8OtRFUvwpEsd9yOLs7QiomTHaJ/rRPU8TA6fKtLHOUisnKiGP47Z3iI+k+VijiuuaJ5hDwmO9Th1WHcwxESxg7ernFdoz27bYjVL6iDtLaUdImtiYUt/GTXPbJVlIbYzGIieucYMdCkmZo4PDbN/heoYmmDmruA8EDG1U+pNNm93gE/XhlY2kvUJ3/uYulIaB0CvAKVAMAk1DKFwZXsLKpxcU=
  template:
    metadata:
      creationTimestamp: null
      name: falkordb-out-of-memory-alert-critical-config-env
      namespace: observability
