---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-crash-alert-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgCf/OVLgEaXb9Ob86NPKHpiHg1f1yUPPcAkP0iN018fyX2/9xkBJmN2Ged0PYXY4QXsRMB6/H1YqlCTyN9MUgRyjmWbnTRB2U2Z9gh1PeL9nXww1wffT2nuaMwFLn5k9ysKsOZNLy5gerG94o6iv6azHYCv8/xTszHz5lwdy4ZRhQP6uU4fWqfxdovxT6oO/oO/u+RJHaFBOkmdqDsEnY9bEIyAfZQdOufIWXi374fZnH3Wyfh193a16Z4XnzR09tn4xml147Rzlegnecxy9Ux1Svgn0kf9HmOcM9rgYil/fcggRT72G0NbMY1EDk5UomeBvqmdQtwgYrVtl4yJPDBfPDkiqInkme9I/fzxkDEnPYEbBaqnUA7Mc4Hzh+uePk3WFw3UUgznbKYjZNIGLWQYI4Iaok+NTA020MmHe+3tx9DZw2GH86samfhU5kxk8gJi5YbMTsm2AU9w5UJGettqiBzSTsq6No1Uo6CJlKFomJ6IFHwThOl0qLg1UulBnggP15q1IfLvfFxLZODn/T3udmg+K1WVSeBJSiCef2wbFst6xe2/dflc4Z8YUulmr+cGR3e85kQxgQjW/9Y3u2kzkX/A3Si/rNF/6dX9bA6B/7cXsSax+MNT7NNQtvc8wpgmXQnujpvfnBh2OmHsY5IpQWkXgX6HfuHU0pJhJ/Ncp+92NJGQaeU1aBjHSOgsuZYM6djzLU2KnKjXS2ZbwImu
    url: AgA6JgL0UgJHV98pD8Ni7hBE6l9W48iiR3ZExuDi71GXgGKhxCD+OHomaHvz4JJKs3qI5WnEUgBeEWeVFfWo7pu6lkFvgOZdQh/0N/81ejT0LS1oJYRX9BV1cRb2bK+OqSrO1NCGf2qyD3oo0RRwQR6SMVpgWdBl53vxljnQeHsyV4EtfYW2+Z/moU8zj/Dr13w/XLh5/18yRb9AO7+1RuLTqLhWAiP8ebHUt5HZySySQgHpJWHz54lj50Y26ZIHFfaUQX/t8pU86fwnj2730lh54yPXiivcQREzc0ZwwFtRM5uRB/0feP9bN0E/96zWZIvOofxd6XFTmCx2LgcUr3A48YoNM4pjy6XT5nECILNUdgDXZPCfWJ3fBRLAFQSmzspGwnvoBhPdpcH/ZgMllq6VcmLz7t75R8mh+phrxw2sQroaqUxk1M3FPlXPMNOwg0drZHD2hC4nhP0k2XkAIoTRwU28AJuXln5YQyl8ZK5RJ87l3mBR/XpT5ffZc0TFTj+kFan8eH9RjEHKGOyoVZ8KBaH2EwaDRJKM9zuOZfLN7FLNE+yCh6Jlk+9J3Ilpx2UrK+l1zy6ygciUbeHPL4fGZ3/o/UmpPmsubzjinvb2DmkxLA4ht7ppnwGXBjH8F0JLJBNftrISuHKKTCmOUy1kulUNzBchi9XgeNxiDYomrIxrbX4BoNqacS/yR7mqX0Hasw3DmY75PH902Lj6n3rmWDFqangdsfhfk0njz1Jl17At/63k3gLQexDLY0Ix6eaOCEZFmYl6zr6gr06wM6d6MK+rKMCJRbXddkU4aRZIQ6S/iN9F0aoD98SSP0VwciQ=
  template:
    metadata:
      creationTimestamp: null
      name: redis-crash-alert-env
      namespace: observability
