---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-crash-alert-env
  namespace: observability
spec:
  encryptedData:
    auth-header: AgA01CVvSiM1B+AAfGlH2NnteWbU3awG0QpWxL1yKHjAQ1uLRVJqoyd4+RLsnM1Ehx4WrBv9OIhuRpNyYm2KZOxNdu8FQ/BNWOaIaAK/xpnFJDPsMgTHLLqiOflXirA4z07Kf0Y4Ngu7Z8+LVBhcym3v4PvGl6TIRNo4JVbVsdhpQHpV+QUoUIId53lndlAJuN+DR9Pk8LeoTrGSpmhClbHfJQUCavTSuIGTbrwCK1Gb5FYhOilVNjy7yjKoHcUCWtrurSYWTkXBL/byLFZVgQBPV+tmssFnyk/zC9jz0bVHUugqEhod+wScQCiuUPua2JJDOLayJyTnXJjomjqkkmkFTdwt8Siev4UWWDsy5/8GRs3au8qfc9WWMwbfoTD4zWHWtY26a+MDs5qC6i7yGkWkVT0LeKT4p8FE4WJXfJ9hHr92fHz9kUTw8541hro+veZj+wf6pVo3FTOVM22wX73QcTjldQnchH76f26h/3gPzoUFJYsIplzU904ip8AxOVmp1QSV9+qe4nUufhcTlWIqt2zhwvtWonhUEz+MJS1IMNwC44q9oipSni9+hIIbtmD3a+TqkOBrqnUISB0TNl40GlW9ITeqFiTzaSuGuoB9QtWaEr0UF9ovgBx2J5LRxOIq56wl3E5TSKvyOA6/Rl1CNhg5T6q9D7+JFU7brB4Gz/rCRZSksWqXN5EDFPA1D+UR2Ci4cXQxCkkp2pwrc5Dg
    url: AgAyFBVFXw5CHpahbecqzcT1FYTIflc+PjBYQuxX65qhhbLb07MYOz4Ajvr+ZMlkXk2MsYOyB2T3Dp0G5ClOkhmggoqqpXBNVgDtGIs7Xwm9iwkXdCaETTTa9hSappChwFkwBX2tKUdH8fsCd+i9dUgdzNJTfJTPC+gmTNObz/YHvZL756PpVZvFGvuNqWt/pcvG2NFcXkBn14P1XJrlPBLERFZ94gyC3OO8M4IpbTP93TgqBStXPchNmfJw4h52iBq4EEWUksSlO8+PFcpe8+9J5fsbBXaaMr+CY69t0xpYyVHRUwFp3NjIYGx49VyvWA4quVujgn+lSvFnyduQaugAnfoqdsBQFawgIqZTMP177bSPZqr4Gp7vV2DXfKabHhxeOltiO9fPlnu9HFh9SLvB4IKOTG3FX+JS6+/62zIlE6j9hTPtViPjKd1fc3OAbtgJUIELaJXSwcyFX8B32e+KCGfYneiYTr6W7v3meKEipKQYJ/veE5mWVsx2Ig6gyb3WDALINKpFLefEKZDxmQpDHRdDWvXs+gRRXIfgD7ByDEUMfUa9OTVaEP6aEvPYt33Zz6Ry+Nhpy6fbzrOzB/wrmwGKMtWLGLeURFu0s69+aTVJ94rrrjdSIqxysmMzvtDX2xw2REoLTLeBwRVAlMcoVNFNa7cI7bLCjxYlkbWx9jnY8tRQ6SkvRb9kmrF/wA8b/IOhfRMXNFOn6asJLyErsXJL3x4jE8GuNxBhKwO8F5OKPHUOONlsYAJsF3VsuAc7bqgihbotQ+UuAbiphhc+kNMXof/kUS1FSIPPkQqepOC2+UQ4mQYYjkLxsA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-crash-alert-env
      namespace: observability
