---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-crash-token
  namespace: observability
spec:
  encryptedData:
    token: AgBTYCegaO309pBpL5sTtuHjOnsZC0YWZZ+1oMv1fl9P8VKw+ZbZV4bYU2ZYEVEM/rkRAoFCEMBCE8Y8zg75PCK3CddkmIkkEi38zUatzRWp9u/wRl9M6kICUu/75a6a8jFHv4SWzxUBrQ87xRd/dsjLWRkqj4bkSN7rngN86MM6F1ma2GAitc/vTxy4N9Vx3eQN2hMAac27fY7cv/8OLbxNlN9usOPm/fAeFgMJ87khJJqaaWkkERYPd4pFAPKAiCM1yOuH3m/vb5z9Pp9dz+5DFSA260ojTnXnSpC2rAvTD1xCzUjqhfwELY5oErelAAivEQAObLlF1lHGQ3Hb/cQg1M7oIe1ChPqqV9aAF6BwAHlY2UIYLTGMgUj4dVXQG2n/dgSeqBsVNcCFia6uhLf9M/1NwEWOOfhDgbriE0awPefU9saJVqsQjXz92sWLAvZNc/7/qoYGKEUEOZLGxpnsNRNGPflO/OiegGqO9hxaAVDxAx9ikgkCGuJfVdn2PZ8Xo15O/JbxotqrUxwJsyhfX/NWNw804GoHv824g0C4+GW2HP6HZl1/4JeLfeXdwgYM/Nc3yGZvcDFFf6Cw0kpHDen4UyYf6SASZxlTh4/Z65/Ivp6L1B0QpQ1l8FnJwOJw8sAqzcSbHmaHtH5JUT0I9ltdk4sWwAiIeN57ATcjagEKd1XyVeqdliOJTG50W4kMAIZwRvG/iod1lIT1XpQ73Xco49+hDFncMgg3BHMwbXTs0ur7KivW
  template:
    metadata:
      name: redis-crash-token
      namespace: observability
