apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/v1/customer-ldap(/|$)(.*) /v1/$2 break;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.dev.falkordb.cloud
      secretName: api-tls
  rules:
    - host: api.dev.falkordb.cloud
      http:
        paths:
          - path: /v1/customer-ldap(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customer-ldap-api
                port:
                  number: 80
          - path: /v1/db-importer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: db-importer
                port:
                  number: 3000
