apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vmuser-metrics-reader-kustomization
namespace: observability
resources:
  - vmuser-metrics-reader.yaml
  - string-secret.yaml